export const services = [
    {
        slug: 'remote-online-notary',
        title: 'Remote Online Notary (RON)',
        image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?q=80&w=1200&auto=format&fit=crop',
        desc: 'Secure audio-visual technology to verify identity and notarize documents online—making it easier than ever to access reliable services from anywhere.',
        icon: 'Globe',
        color: 'bg-blue-50 text-blue-600',
        fullDesc: 'Wherever you are in the world, The Global Notariat brings the notary to you. Our Remote Online Notary (RON) services allow you to legally and securely notarize documents from the comfort of your home, office, or anywhere with internet access. Commissioned in Florida and authorized under U.S. law, our notaries use secure audio-visual technology to verify identity and notarize documents online—making it easier than ever for clients across the nation and around the globe to access reliable notarial services.',
        features: [
            'U.S. citizens living or traveling abroad',
            'International clients with U.S. entities',
            'College students and professionals',
            'Military personnel and expats',
            'Real estate, legal, and healthcare needs',
            'Fast, secure, and encrypted platform',
            'Available 7 days a week by appointment'
        ],
    },
    {
        slug: 'mobile-notary',
        title: 'Mobile Notary Services',
        image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=1200&auto=format&fit=crop',
        desc: 'We bring the notary to your door. Prompt and reliable services tailored to your schedule across Central Florida and beyond.',
        icon: 'Shield',
        color: 'bg-blue-900/5 text-primary-navy',
        fullDesc: 'At The Global Notariat, we are proud to provide professional, reliable, and accessible notary services tailored to the needs of today\'s fast-paced and connected world. Based in Central Florida, we offer Mobile Notary Services throughout the region—bringing trusted notarial services directly to your door. For clients across the United States and beyond, our Remote Online Notary (RON) capabilities allow us to securely notarize documents anytime, anywhere in the world. Whether you\'re down the street or across the globe, The Global Notariat is your trusted partner to serve with integrity, precision, and convenience.',
        features: [
            'Available 24/7 for your convenience',
            'In-person signature verification',
            'Travel to homes, offices, and hospitals',
            'Prompt and punctual service',
            'Serving all of Central Florida'
        ],
    },
    {
        slug: 'loan-signing',
        title: 'Loan Signing Services',
        image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=1200&auto=format&fit=crop',
        desc: 'Professional loan signing agents for mortgage lenders, title companies, and signing agencies. Accuracy and confidentiality guaranteed.',
        icon: 'FileText',
        color: 'bg-orange-50 text-orange-600',
        fullDesc: 'We provide loan signing services for mortgage lenders, title companies, and signing agencies. Our notary will ensure that all loan documents are correctly signed and notarized. We understand the critical nature of loan closings and provide a seamless, error-free experience for your clients.',
        features: [
            'Buyer and Seller Package Signings',
            'Refinance Document Signings',
            'Loan Modifications & Reverse Mortgages',
            'HELOC (Home Equity Line of Credit)',
            'Commercial Loan Closings',
            'Deeds of Trust and Promissory Notes',
            'Escrow and Settlement Documents',
            'Scanbacks / Document Drop-off',
            'Same-Day and After-Hours Signings'
        ],
    },
    {
        slug: 'apostille-authentication',
        title: 'Apostille & Authentication',
        image: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?q=80&w=1200&auto=format&fit=crop',
        desc: 'Official document authentication for international use. We handle the complex paperwork so your documents are globally accepted.',
        icon: 'Award',
        color: 'bg-purple-50 text-purple-600',
        fullDesc: 'Need to use U.S. documents internationally? We’ve got you covered. At The Global Notariat, we offer Apostille and document authentication services to ensure your paperwork is legally recognized in foreign countries. Whether you’re submitting documents for international adoption, business registration, overseas education, or dual citizenship, we handle the process for you—accurately and efficiently.',
        features: [
            'Birth, marriage, and death certificates',
            'Power of Attorney for overseas use',
            'Corporate documents for international business',
            'Educational diplomas and transcripts',
            'FBI background checks and court documents',
            'Embassy and consulate legalizations',
            'Hassle-free, reliable, and globally accepted'
        ],
    },
    {
        slug: 'wedding-officiant',
        title: 'Wedding Officiant',
        image: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?q=80&w=1200&auto=format&fit=crop',
        desc: 'Professional and memorable wedding ceremonies tailored to your preferences. Helping you celebrate love with integrity.',
        icon: 'Gavel',
        color: 'bg-pink-50 text-pink-600',
        fullDesc: 'At The Global Notariat, we believe that every union deserves a memorable and meaningful ceremony. In addition to our notarial services, we are proud to offer wedding officiating services for couples seeking a professional and personal touch for their special day. Whether you’re planning a small, intimate gathering or a grand celebration, our wedding notaries—authorized to perform wedding ceremonies in Florida—are here to help you say “I do” in a way that reflects your values and vision.',
        features: [
            'Custom civil ceremonies',
            'Elopements and destination weddings',
            'Last-minute or same-day officiation',
            'Marriage license filing assistance',
            'Bilingual ceremonies available',
            'Professionalism and attention to detail'
        ],
    },
    {
        slug: 'healthcare-senior-living',
        title: 'Healthcare and Senior Living',
        image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=1200&auto=format&fit=crop',
        desc: 'Sensitive and senior-friendly approach for medical directives. We ensure patients and residents get the service they need.',
        icon: 'Heart',
        color: 'bg-teal-50 text-teal-600',
        fullDesc: 'We provide specialized notary services for medical directives, ensuring that they are properly executed and notarized. Our notaries are trained to handle sensitive documents like Advanced Health Directives, Medical Powers of Attorney, and Living Wills with the utmost care and patience. We travel directly to patient bedsides or private residences to ensure that critical legal documents are executed correctly and comfortably.',
        features: [
            'Mobile Notary for Patients and Residents',
            'Coordination with Facility Staff',
            'Sensitive and Senior-Friendly Approach',
            'Available within 30 mins in Central FL',
            'Medical Powers of Attorney (POA)',
            'Advanced Directives / Living Wills'
        ],
    },
    {
        slug: 'expatriates-worldwide',
        title: 'Serving Expatriates Worldwide',
        image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?q=80&w=1200&auto=format&fit=crop',
        desc: 'Living abroad doesn\'t mean you\'re out of reach for essential U.S.-based notarizations. Seamless digital connection.',
        icon: 'Globe',
        color: 'bg-indigo-50 text-indigo-600',
        fullDesc: 'Living abroad doesn’t mean you’re out of reach for essential U.S.-based notarizations. At The Global Notariat, we specialize in helping American expatriates and global citizens get their important documents notarized—no matter where in the world they are. Whether you’re handling property transactions, legal paperwork, or personal authorizations, our Remote Online Notary (RON) services ensure recognized back home.',
        features: [
            'Power of Attorney for use in the U.S.',
            'Affidavits and legal declarations',
            'Parental consent forms for minors',
            'Real estate and financial documents',
            'IRS and immigration-related forms',
            'Secure, Accessible, Always on time'
        ],
    },
    {
        slug: 'business-financial-documents',
        title: 'Business and Financial',
        image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?q=80&w=1200&auto=format&fit=crop',
        desc: 'We understand the importance of accuracy, confidentiality, and timeliness when handling business and financial documents.',
        icon: 'Briefcase',
        color: 'bg-gray-50 text-gray-700',
        fullDesc: 'In the fast-paced business world, efficiency and accuracy are non-negotiable. We understand the importance of accuracy, confidentiality, and timeliness when handling business and financial documents. Whether you’re establishing a new business, authorizing transactions, or executing your critical contracts, our notarial services ensure your documents are properly authenticated and legally binding. We provide seamless notarization for a wide range of business needs.',
        features: [
            'Contracts and Agreements',
            'Articles of Incorporation',
            'Operating Agreements and Resolutions',
            'Financial Affidavits',
            'Letters of Authorization',
            'Business Formation Documents'
        ],
    },
    {
        slug: 'college-students',
        title: 'Student Notary Services',
        image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=1200&auto=format&fit=crop',
        desc: 'Fast, convenient, and secure notary services for students. Enrollment verification, study abroad affidavits, and more.',
        icon: 'GraduationCap',
        color: 'bg-blue-50 text-blue-700',
        fullDesc: 'Navigating campus life often involves important paperwork—and The Global Notariat is here to help. We provide fast, convenient, and secure notary services for students, whether you’re on-campus, off-campus, or studying remotely. From verifying enrollment to notarizing parental consent forms, we make the process simple and accessible.',
        features: [
            'Enrollment verification forms',
            'Study abroad affidavits',
            'Parental consent forms',
            'Student loan documents',
            'Housing and lease agreements',
            'Power of attorney for healthcare',
            'Internship authorization forms'
        ],
    },
    {
        slug: 'estate-planning',
        title: 'Estate Planning Documents',
        image: 'https://images.unsplash.com/photo-1505664194779-8beaceb93744?q=80&w=1200&auto=format&fit=crop',
        desc: 'Experienced in notarizing estate planning documents such as wills, trusts, and power of attorney documents.',
        icon: 'FileCheck',
        color: 'bg-red-50 text-red-700',
        fullDesc: 'Estate planning is a critical step in securing your future and protecting your loved ones. Our notary is experienced in notarizing estate planning documents such as wills, trusts, and power of attorney documents. We ensure that every document is executed with the highest degree of accuracy and legal compliance.',
        features: [
            'Last Will and Testament',
            'Living Trusts',
            'Powers of Attorney (POA)',
            'Healthcare Directives',
            'Trust Amendments',
            'Executor Designations'
        ],
    },
];
